### ISSUE TITLE
Bot not forwarding...

### ISSUE THREAD

**Issue by millerk123** [MrMissx/Telegram_Forwarder#102]
Hello,

I have followed your configure instructions, and I am able to run the bot.  I've got my bot token in correctly, and it shows in the terminal that the bot is running.  However, the messages are not forwarded as I request.  I found my OWNER_ID from the raw_data_bot tg bot.  Is there anything else that I need to do?

I saw some things online about two-factor authentication?

Thanks,
Kyle

**Comment by MrMissx** [comment]
Hi,

OWNER_ID doesn't affect anything to the forwarding ability. Make sure your bot privacy setting were off from botfather. This make sure the bot receive all message event.

**Comment by millerk123** [comment]
I see.  And I guess the bot has to be a member of whatever channel/group I'm forwarding from/to?

**Comment by MrMissx** [comment]
Yes the bot must be a member of the chat/channel source and destination

**Comment by Onair-santa** [comment]
Not work forwarding. Privacy off. Bot in channel destination. Bot work but messages not forwarding
