### ISSUE TITLE
Bot_TelegramForwarder; can't forward messages sent by bots

### ISSUE THREAD

**Issue by norm-git** [MrMissx/Telegram_Forwarder#56]
Hello there,
Bot Forward are not forwarding messages sent by other bots in a group
Other bots, can be mirror-bot, rssbot, Modularbot
Please if you can verify this issue and try to fix it

Using Mode Forward Bot
 FROM_CHAT ID of a group
 TO_CHAT ID OF a channel

_I have not tried From Channel to Channel or From Channel to Group yet_

**Comment by MrMissx** [comment]
Hi
As far as i know a bot won't trigger a message update to other bot. So, you couldn't forward a message sent by other bot (unless you forward it manually). A workaround for this case is by using a channel that your other bot sent to.

**Comment by norm-git** [comment]
> Hi As far as i know a bot won't trigger a message update from other bot message. So, you couldn't forward a message sent by other bot (unless you forward it manually). A workaround for this case is by using a channel that your other bot sent to.

**Comment by MrMissx** [comment]
it is not possible in a group chat. You should use a channel instead.
should be working if you're using a userbot.
