### ISSUE TITLE
Installed and ran everything but nothing happens

### ISSUE THREAD

**Issue by misterpeople** [MrMissx/Telegram_Forwarder#57]
Hey so i made the bot admin in both groups , I set up the config file and ran the bot.
the bot runs when I do /start.
I get this message : " 2021-10-06 23:19:02,684 - forwarder - INFO - Using long polling.
2021-10-06 23:19:02,685 - apscheduler.scheduler - INFO - Scheduler started"

seems like everything running well but I sent a message to test and it wont forward anything.

**Comment by misterpeople** [comment]
Pretty sure they are good, I will check again, does it also forwarded posts with pictures and videos?

**Comment by nguyennhulonggithub** [comment]
You need to set privacy of your bot in BotFather to "Disable". That make the bot can read message from the chat

**Comment by Shehab37** [comment]
> You need to set privacy of your bot in BotFather to "Disable". That make the bot can read message from the chat

that helped a lot ,  thanks
