### ISSUE TITLE
Can't deploy to heroku: Source code violates the Salesforce Acceptable Use

### ISSUE THREAD

**Issue by Arianbakhtou** [MrMissx/Telegram_Forwarder#65]
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy

what is this error

**Comment by MrMissx** [comment]
Fixed this by forking this repo then deploy with the following link
`https://heroku.com/deploy?template=https://github.com/<YourGithubUsername>/Telegram_Forwarder`

Change `YourGithubUsername` with yours

*I don't really know what the cause of this Salesforce thing.
