### ISSUE TITLE
delay option 

### ISSUE THREAD

**Issue by somedevreally** [MrMissx/Telegram_Forwarder#71]
hello,

can we have a delay option?  so for example if multiple message are posted in "from chat" it should not flood "to chat" and should send with few seconds delay between messages

thanks

**Comment by MrMissx** [comment]
Hi.
Its been a while since I'm working on this project. If you want to implement this I would happy to have a pull request. 
Thank you

**Comment by somedevreally** [comment]
didn't realize this project is abandoned.
thanks
