### ISSUE TITLE
TOPIC 

### ISSUE THREAD

**Issue by prono69** [MrMissx/Telegram_Forwarder#81]
Can you add support for Forum topic ?

**Comment by MrMissx** [comment]
you can use topic only in destination config with `"chat_id#topic_id"` prefix. https://github.com/MrMissx/Telegram_Forwarder#chat_listjson

**Comment by prono69** [comment]
Thank you very much 😊
But is it possible to add topic in source too ? Like gey files from specific topic from source chat and send it to specific topic in destination chat ?

**Comment by MrMissx** [comment]
I currently don't have the use case for that such behavior thus I'm not working on it soon. I would be happy if you send a PR to me.
I'll reopen this issue until it is resolved 🙂.

**Comment by IlBudda** [comment]
Having a topic as the source would be amazing
