### ISSUE TITLE
[Feature Request] Add keywords filter and blacklist

### ISSUE THREAD

**Issue by noobietele** [MrMissx/Telegram_Forwarder#94]
[
  {
    "source": -10012345678,
    "destination": [-10011111111, "-10022222222#123456"]
  },
  {
    "source": "-10087654321#000000",  // Topic/Forum group
    "destination": ["-10033333333#654321"]
  }
]

how to add filter for keywords ?? different for each source to destination ??

**Comment by noobietele** [comment]
i found this repo https://github.com/noobietele/telegram-forwarder_auto ,,, like that blocked texts variable ,can we get both blocked text & whitelist text in env for each source to destination ??

**Comment by MrMissx** [comment]
keyword filtering currently not supported yet

**Comment by noobietele** [comment]
If possible check this out ,https://github.com/aahnik/tgcf , it just need multiple source to destination forward and topics support from your repo.

**Comment by MrMissx** [comment]
keyword filters and blacklist added on 2.3.0

**Comment by noobietele** [comment]
Thanks
