### ISSUE TITLE
Forward Bot Messages ??

### ISSUE THREAD

**Issue by noobietele** [MrMissx/Telegram_Forwarder#95]
It only forwards users messages but doesn't forward bot messages ,it it possible to foward all messages either bot or user ??

**Comment by MrMissx** [comment]
No, that's not currently possible. There is a Telegram limitation that a bot can't see other bot messages, therefore it would not forward the message

**Comment by noobietele** [comment]
https://github.com/aahnik/tgcf  Check this out ,it can also forward bot messages,maybe it can help (missing topics and multiple forwarder support) , its like, if this and your repo can be combined it will be a perfect forward bot .

**Comment by MrMissx** [comment]
those project uses another libs that use a real user account (uses API ID and API KEY) not a bot account (uses BOT TOKEN), and I'm not planning to implement that kind of feature as it will be a complete rewrite.

**Comment by noobietele** [comment]
oh ok thanks
