### ISSUE TITLE
Request for user session insted of bot

### ISSUE THREAD

**Issue by Amiinnetdz** [MrMissx/Telegram_Forwarder#96]
Please if you can add text filter and text replace 
Add user session to connect with user instead of bot for forward from private channel.
Api_id
Api_hash
session

**Comment by MrMissx** [comment]
You can't use a user session as we only use the BOT API to connect to Telegram (more context here https://github.com/MrMissx/Telegram_Forwarder/issues/95#issuecomment-1915963806)

The word filtering is planed by this issue https://github.com/MrMissx/Telegram_Forwarder/issues/94 but I can't give any ETA
