### ISSUE TITLE
Any idea why it's not working? I did the json correctly, but it's not passing through 

### ISSUE THREAD

**Issue by skdplay** [MrMissx/Telegram_Forwarder#99]
Any idea why it's not working? I did the json correctly, but it's not passing through

**Comment by MrMissx** [comment]
can you provide logs?

**Comment by espinozasenior** [comment]
Same to me, nothing happens!
I can't provide logs because nothing happens, bot start ok but seems it doesn't detect target channel messages.

I'm using Python 3.12

**Comment by espinozasenior** [comment]
Ok, I think I already understand. 
Only it works through the bot (bot token) and I was searching through my Telegram account. To do this it must be through a session_token. In my case, the messages that I want to forward do not have permissions to include the bot within the chats or channels.
